# Generated by Django 4.2.14 on 2024-07-27 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_patient_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('patientname', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
    ]
