# Generated by Django 4.2.14 on 2024-07-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_consultation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='patientname',
        ),
        migrations.AddField(
            model_name='consultation',
            name='idpatient',
            field=models.IntegerField(default=1),
        ),
    ]
