# Generated by Django 4.2.14 on 2024-07-27 14:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_consultation_patientname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='idpatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.patient'),
        ),
    ]
